### ISSUE TITLE
support for 0.3.x versions

### ISSUE THREAD

**Issue by flavioribeiro** [kslimani/clappr-playback-boilerplate#1]
when testing this boilerplate, it works up until the 0.2.100 version but breaks with Kibo integration on 0.3.x.

**Comment by kslimani** [comment]
I upgraded dependencies, and i updated the Clappr configuration on index page. This issue was due to using `parent` configuration option instead of `parentId`.

@flavioribeiro  could you please confirm it fix also for you ?

**Comment by flavioribeiro** [comment]
yep, that's working now. thanks!
